---
version: 3

vars:
  BINARY_NAME: gitgrab
  REPO: github.com/scottbrown/{{.BINARY_NAME}}
  BUILD_DIR: .build
  DIST_DIR: .dist
  TEST_DIR: .test
  VERSION:
    sh: |
      if [ -n "$GITHUB_REF" ] && [[ "$GITHUB_REF" == refs/tags/* ]]; then
        echo "${GITHUB_REF#refs/tags/}"
      else
        git rev-parse --abbrev-ref HEAD || echo "main"
      fi
  BUILD:
    sh: git rev-parse --short HEAD || echo "unknown"
  BUILD_FLAGS: "-X {{.REPO}}.version={{.VERSION}} -X {{.REPO}}.build={{.BUILD}}"

tasks:
  setup:
    internal: true
    run: once
    cmds:
      - mkdir -p {{.BUILD_DIR}}
      - mkdir -p {{.DIST_DIR}}
      - mkdir -p {{.TEST_DIR}}

  build:
    desc: "Builds a local binary"
    cmds:
      - go build -ldflags "{{.BUILD_FLAGS}}" -o {{.BUILD_DIR}}/{{.BINARY_NAME}} {{.REPO}}/cmd/{{.BINARY_NAME}}
    sources:
      - '**/*.go'
    generates:
      - '{{.BUILD_DIR}}/{{.BINARY_NAME}}'

  clean:
    desc: "Removes all temporary files and directories"
    cmds:
      - rm -rf {{.BUILD_DIR}} {{.DIST_DIR}} {{.TEST_DIR}}

  fmt:
    desc: "Formats the code"
    cmds:
      - go fmt ./...

  test:
    desc: "Runs unit tests"
    cmds:
      - go test -v ./... -outputdir={{.TEST_DIR}}

  coverage:
    desc: "Prints the current test coverage"
    cmds:
      - go test ./... -cover

  check:
    desc: "Run all security scans"
    deps: [ sast, vet, vuln ]

  sast:
    desc: "Scans for code vulns"
    cmds:
      - gosec ./...

  vet:
    desc: Lint Go code
    cmds:
      - go vet ./...

  vuln:
    desc: "Scans for 3rd party lib vulns"
    cmds:
      - govulncheck ./...


  release:
    desc: Build release artifacts for multiple platforms
    cmds:
      - task: clean
      - task: setup
      - task: release-darwin
      - task: release-linux
      - task: release-windows

  release-darwin:
    cmds: [task: release-darwin-amd64, task: release-darwin-arm64]
  release-linux:
    cmds: [task: release-linux-amd64, task: release-linux-arm64]
  release-windows:
    cmds: [task: release-windows-amd64, task: release-windows-arm64]

  release-core:
    internal: true
    env:
      GOOS: linux
      GOARCH: amd64
    cmds:
      - tar -czf {{.DIST_DIR}}/{{.BINARY_NAME}}-{{.VERSION}}-{{.GOOS}}-{{.GOARCH}}.tar.gz -C {{.BUILD_DIR}}/{{.GOOS}}-{{.GOARCH}} {{.BINARY_NAME}}{{.FILE_EXT}}

  release-linux-amd64:
    cmds:
      - task: build-linux-amd64
      - task: release-core
        vars: { GOOS: linux, GOARCH: amd64 }
      
  release-linux-arm64:
    cmds:
      - task: build-linux-arm64
      - task: release-core
        vars: { GOOS: linux, GOARCH: arm64 }
      
  release-windows-amd64:
    cmds:
      - task: build-windows-amd64
      - task: release-core
        vars: { GOOS: windows, GOARCH: amd64, FILE_EXT: ".exe" }
      
  release-windows-arm64:
    cmds:
      - task: build-windows-arm64
      - task: release-core
        vars: { GOOS: windows, GOARCH: arm64, FILE_EXT: ".exe" }
      
  release-darwin-amd64:
    cmds:
      - task: build-darwin-amd64
      - task: release-core
        vars: { GOOS: darwin, GOARCH: amd64 }
      
  release-darwin-arm64:
    cmds:
      - task: build-darwin-arm64
      - task: release-core
        vars: { GOOS: darwin, GOARCH: arm64 }
